import { FileItem } from '../types';
import { getFileCategory } from './formatters';

export function createSampleFile(
  name: string,
  size: number,
  type: string,
  content: string = 'Sample file payload content generated by DropLink.'
): FileItem {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const category = getFileCategory(name, type);

  return {
    id: 'sample-' + Math.random().toString(36).substring(2, 9),
    name,
    size,
    type: category,
    mimeType: type,
    blobUrl: url,
    dataUrl: url,
  };
}

export function getPresetSampleFiles(): FileItem[] {
  return [
    createSampleFile('Vacation_Photo_4K.jpg', 4.8 * 1024 * 1024, 'image/jpeg', 'Fake image data binary string for DropLink testing'),
    createSampleFile('Project_Presentation.pdf', 12.4 * 1024 * 1024, 'application/pdf', 'Fake PDF presentation slides content'),
    createSampleFile('DropLink_Android_v2.4.apk', 28.5 * 1024 * 1024, 'application/vnd.android.package-archive', 'Fake Android APK binary installer package'),
    createSampleFile('Ambient_Chill_Audio.mp3', 8.2 * 1024 * 1024, 'audio/mpeg', 'Fake MP3 sound file content'),
    createSampleFile('Source_Code_Backup.zip', 45.1 * 1024 * 1024, 'application/zip', 'Fake zip archive contents'),
  ];
}
